"""Copy DRIFT's recorded evidence into site-v2 and write evidence.js.

Run from the repository root:  python site-v2/build_evidence.py
It only READS the project's artifacts and contracts. It changes nothing else.
"""
import json, pathlib, shutil
root = pathlib.Path(__file__).resolve().parent.parent
site = pathlib.Path(__file__).resolve().parent
out = site / "evidence"; out.mkdir(exist_ok=True)
files = {
    "tmp117": root / "artifacts" / "verification.json",
    "bme280": root / "artifacts" / "bme280_verification.json",
    "tmp117_contract": root / "contracts" / "tmp117.approved.json",
    "bme280_contract": root / "contracts" / "bme280.approved.json",
}
diff_path = root / "artifacts" / "repair_diff.patch"
bundle = {}
for key, p in files.items():
    shutil.copy2(p, out / p.name)
    bundle[key] = json.loads(p.read_text(encoding="utf-8"))
shutil.copy2(diff_path, out / diff_path.name)
bundle["repair_diff"] = diff_path.read_text(encoding="utf-8").replace("\r\n", "\n")
bundle["files"] = {k: "evidence/" + p.name for k, p in files.items()}
bundle["files"]["repair_diff"] = "evidence/" + diff_path.name
(site / "evidence.js").write_text(
    "/* Generated by build_evidence.py from the DRIFT repository. Do not edit by hand. */\n"
    "window.DRIFT_EVIDENCE = " + json.dumps(bundle, ensure_ascii=False) + ";\n",
    encoding="utf-8")
print("evidence.js written;", {k: len(v["runs"]) for k, v in bundle.items() if isinstance(v, dict) and "runs" in v})
